Add "log" and "restash"

diff --git a/bin/gt b/bin/gt
--- a/bin/gt
+++ b/bin/gt
@@ -97,6 +97,12 @@ case "$op" in
         git diff "$@"
 	;;
 
+    log)
+       colors='--format=format:%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(dim white) - %an%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n %C(white)%s%C(reset)'
+	git log --graph --abbrev-commit --decorate --all "${colors}" "$@"
+        echo ''
+	;;
+
     make-gh-pages)
         url=`git config --get remote.origin.url`
 	base=`basename "$url" .git`
@@ -176,6 +182,21 @@ case "$op" in
 	# Push all local changes to the origin/repo server
         set_branch
 	git push --dry-run origin $branch
+	;;
+
+    restash)
+	## Untried
+	git stash
+	if [ $? -ne 0 ]; then
+	    echo "stash failed"
+	    exit 1
+	fi
+	git pull --rebase
+        if [ $? -ne 0 ]; then
+            echo "rebase failed"
+            exit 1
+        fi
+	git stash pop
 	;;
 
     st|stat|status)
